replicaCount: 2
image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

container:
  port: 8080

service:
  annotations: {}
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


resources: 
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /health-z
    port: http
readinessProbe:
  httpGet:
    path: /health-z
    port: http

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 200
  targetMemoryUtilizationPercentage: 800

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

domains:
  - example.com
env:
  VIPS_CONCURRENCY: 1
  MAX_WORKERS: 2
  GOMAXPROCS: 1